name: Deploy

on: [push]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git for cloning
        run: git config --global url."https://${{ secrets.API_TOKEN_GITHUB }}:@github.com/".insteadOf "https://github.com/"
      - name: Get Branch Name
        id: get_branch
        run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: creates output
        run: git clone -b ${{ env.branch }} https://github.com/gastawny/eng-software.git
      - name: git log
        run: git log
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'eng-software'
          destination-github-username: 'thick3USR'
          destination-repository-name: 'eng-software'
          user-email: github.thick3@gmail.com
          target-branch: ${{ env.branch }}
          create-target-branch-if-needed: true
