name: Deploy

on:
  push:
    branches:
      - '**'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch Name
        run: echo ${GITHUB_REF##*/}
